require("configs.general")
require("configs.mappings")
require("configs.terminal")

require("plugins.nvim-web-devicons")
require("plugins.treesitter")
require("plugins.gruvbox")
require("plugins.telescope")
require("plugins.mason")
require("plugins.blink")
require("plugins.lualine")
require("plugins.nvim-tree")
require("plugins.treesitter-context")
require("plugins.luasnip")
require("plugins.trailspace")
require("plugins.vs-tasks")

require("configs.lsp_settings")
