-- Generated by HyprMon. Manual changes may be overwritten.

hl.monitor({ output = "eDP-1", disabled = true })
hl.monitor({ output = "DP-10", mode = "2560x1440@59.95", position = "3852x-544", scale = 1.00, transform = 1 })
hl.monitor({ output = "DP-11", mode = "2560x1440@59.95", position = "5312x32", scale = 1.00 })
