-- Generated by HyprMon. Manual changes may be overwritten.

hl.monitor({ output = "eDP-1", disabled = true })
hl.monitor({ output = "DP-12", mode = "2560x1440@59.95", position = "-4065x-544", scale = 1.00, transform = 1 })
hl.monitor({ output = "DP-13", mode = "2560x1440@59.95", position = "-2625x96", scale = 1.00 })
