-- Generated by HyprMon. Manual changes may be overwritten.

hl.monitor({ output = "eDP-1", disabled = true })
hl.monitor({ output = "DP-10", mode = "2560x1440@59.95", position = "0x0", scale = 1, transform = 1 })
hl.monitor({ output = "DP-11", mode = "2560x1440@59.95", position = "1440x580", scale = 1 })
